url: https://progressivewildwest.org
baseurl: /
title: Progressive Wild West

source:         .
destination:    ./_site
plugins_dir:    ./_plugins

markdown:       kramdown
permalink:      date

kramdown:
    auto_ids: true,
    footnote_nr: 1
